#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0xA744CDAFDBE1D719 (aleixpol@kde.org)
#
Name     : plasma-wayland-protocols
Version  : 1.5
Release  : 7
URL      : https://download.kde.org/stable/plasma-wayland-protocols/plasma-wayland-protocols-1.5.tar.xz
Source0  : https://download.kde.org/stable/plasma-wayland-protocols/plasma-wayland-protocols-1.5.tar.xz
Source1  : https://download.kde.org/stable/plasma-wayland-protocols/plasma-wayland-protocols-1.5.tar.xz.sig
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-3-Clause LGPL-2.1 LGPL-3.0 MIT
Requires: plasma-wayland-protocols-data = %{version}-%{release}
Requires: plasma-wayland-protocols-license = %{version}-%{release}
BuildRequires : buildreq-cmake
BuildRequires : buildreq-kde
BuildRequires : extra-cmake-modules-data
BuildRequires : pkg-config
BuildRequires : pkgconfig(wayland-protocols)

%description
# Plasma Wayland Protocols
This project should be installing only the xml files of the non-standard wayland
protocols we use in Plasma.

%package data
Summary: data components for the plasma-wayland-protocols package.
Group: Data

%description data
data components for the plasma-wayland-protocols package.


%package dev
Summary: dev components for the plasma-wayland-protocols package.
Group: Development
Requires: plasma-wayland-protocols-data = %{version}-%{release}
Provides: plasma-wayland-protocols-devel = %{version}-%{release}
Requires: plasma-wayland-protocols = %{version}-%{release}

%description dev
dev components for the plasma-wayland-protocols package.


%package license
Summary: license components for the plasma-wayland-protocols package.
Group: Default

%description license
license components for the plasma-wayland-protocols package.


%prep
%setup -q -n plasma-wayland-protocols-1.5
cd %{_builddir}/plasma-wayland-protocols-1.5

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1636121916
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
%cmake ..
make  %{?_smp_mflags}
popd

%install
export SOURCE_DATE_EPOCH=1636121916
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/plasma-wayland-protocols
cp %{_builddir}/plasma-wayland-protocols-1.5/COPYING.LIB %{buildroot}/usr/share/package-licenses/plasma-wayland-protocols/9a1929f4700d2407c70b507b3b2aaf6226a9543c
cp %{_builddir}/plasma-wayland-protocols-1.5/LICENSES/BSD-3-Clause.txt %{buildroot}/usr/share/package-licenses/plasma-wayland-protocols/9950d3fdce1cff1f71212fb5abd31453c6ee2f8c
cp %{_builddir}/plasma-wayland-protocols-1.5/LICENSES/LGPL-2.1-only.txt %{buildroot}/usr/share/package-licenses/plasma-wayland-protocols/3c3d7573e137d48253731c975ecf90d74cfa9efe
cp %{_builddir}/plasma-wayland-protocols-1.5/LICENSES/LGPL-2.1-or-later.txt %{buildroot}/usr/share/package-licenses/plasma-wayland-protocols/6f1f675aa5f6a2bbaa573b8343044b166be28399
cp %{_builddir}/plasma-wayland-protocols-1.5/LICENSES/LGPL-3.0-only.txt %{buildroot}/usr/share/package-licenses/plasma-wayland-protocols/757b86330df80f81143d5916b3e92b4bcb1b1890
cp %{_builddir}/plasma-wayland-protocols-1.5/LICENSES/LicenseRef-KDE-Accepted-LGPL.txt %{buildroot}/usr/share/package-licenses/plasma-wayland-protocols/e458941548e0864907e654fa2e192844ae90fc32
cp %{_builddir}/plasma-wayland-protocols-1.5/LICENSES/LicenseRef-KDE-Accepted-LGPL.txt %{buildroot}/usr/share/package-licenses/plasma-wayland-protocols/e458941548e0864907e654fa2e192844ae90fc32
cp %{_builddir}/plasma-wayland-protocols-1.5/LICENSES/MIT.txt %{buildroot}/usr/share/package-licenses/plasma-wayland-protocols/a0193e3fccf86c17dc71e3f6c0ac0b535e06bea3
pushd clr-build
%make_install
popd

%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/plasma-wayland-protocols/appmenu.xml
/usr/share/plasma-wayland-protocols/blur.xml
/usr/share/plasma-wayland-protocols/contrast.xml
/usr/share/plasma-wayland-protocols/dpms.xml
/usr/share/plasma-wayland-protocols/fake-input.xml
/usr/share/plasma-wayland-protocols/fullscreen-shell.xml
/usr/share/plasma-wayland-protocols/idle.xml
/usr/share/plasma-wayland-protocols/kde-output-device-v2.xml
/usr/share/plasma-wayland-protocols/kde-output-management-v2.xml
/usr/share/plasma-wayland-protocols/keystate.xml
/usr/share/plasma-wayland-protocols/output-management.xml
/usr/share/plasma-wayland-protocols/outputdevice.xml
/usr/share/plasma-wayland-protocols/plasma-shell.xml
/usr/share/plasma-wayland-protocols/plasma-virtual-desktop.xml
/usr/share/plasma-wayland-protocols/plasma-window-management.xml
/usr/share/plasma-wayland-protocols/remote-access.xml
/usr/share/plasma-wayland-protocols/screencast.xml
/usr/share/plasma-wayland-protocols/server-decoration-palette.xml
/usr/share/plasma-wayland-protocols/server-decoration.xml
/usr/share/plasma-wayland-protocols/shadow.xml
/usr/share/plasma-wayland-protocols/slide.xml
/usr/share/plasma-wayland-protocols/surface-extension.xml
/usr/share/plasma-wayland-protocols/text-input-unstable-v2.xml
/usr/share/plasma-wayland-protocols/text-input.xml
/usr/share/plasma-wayland-protocols/wayland-eglstream-controller.xml

%files dev
%defattr(-,root,root,-)
/usr/lib64/cmake/PlasmaWaylandProtocols/PlasmaWaylandProtocolsConfig.cmake
/usr/lib64/cmake/PlasmaWaylandProtocols/PlasmaWaylandProtocolsConfigVersion.cmake

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/plasma-wayland-protocols/3c3d7573e137d48253731c975ecf90d74cfa9efe
/usr/share/package-licenses/plasma-wayland-protocols/6f1f675aa5f6a2bbaa573b8343044b166be28399
/usr/share/package-licenses/plasma-wayland-protocols/757b86330df80f81143d5916b3e92b4bcb1b1890
/usr/share/package-licenses/plasma-wayland-protocols/9950d3fdce1cff1f71212fb5abd31453c6ee2f8c
/usr/share/package-licenses/plasma-wayland-protocols/9a1929f4700d2407c70b507b3b2aaf6226a9543c
/usr/share/package-licenses/plasma-wayland-protocols/a0193e3fccf86c17dc71e3f6c0ac0b535e06bea3
/usr/share/package-licenses/plasma-wayland-protocols/e458941548e0864907e654fa2e192844ae90fc32
